name: Vagrant up
on: 
 pull_request:
jobs:
  k3s-1-23:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install -y libvirt-clients libvirt-daemon-system
      - name: Run test
        run: ./ci/test-pr.sh
