name: Build PR
on: 
 pull_request:
jobs:
  qemu-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install -y libvirt-clients libvirt-daemon-system
          sudo virsh list --all
          sudo curl -sfL https://github.com/mikefarah/yq/releases/download/v4.25.1/yq_linux_amd64 -o /usr/local/bin/yq && sudo chmod +x /usr/local/bin/yq
      - name: Run test
        run: ./ci/test-pr.sh
